### ISSUE TITLE
Crash on startup on master branch

### ISSUE THREAD

**Issue by kenrestivo** [poljar/weechat-matrix#290] opened 2021-08-18 03:51 UTC
```
              │20:48:07 matrix_org  -- | matrix: Logging in...
               │20:48:07 matrix_org  -- | matrix: Logged in as @redacted:matrix.org
               │20:48:09    weechat     | python: stdout/stderr (matrix): Traceback (most recent call last):
               │20:48:09    weechat     | python: stdout/stderr (matrix):   File
               │                        | "/home/lken/.weechat/python/matrix/utf.py", line 89, in wrapper
               │20:48:09    weechat     | python: stdout/stderr (matrix):     return function(*args, **kwargs)
econd time      20:48:09    weechat     | python: stdout/stderr (matrix):   File
               │                        | "/home/lken/.weechat/python/autoload/matrix.py", line 334, in receive_cb
               │20:48:09    weechat     | python: stdout/stderr (matrix):     response = server.client.next_response()
               │20:48:09    weechat     | python: stdout/stderr (matrix):   File
               │                        | "/usr/local/lib/python3.9/dist-packages/nio/client/http_client.py", line

eechat      │                        | "/usr/local/lib/python3.9/dist-packages/nio/client/http_client.py", line
               │                        | 1342, in next_response
               │20:48:09    weechat     | python: stdout/stderr (matrix):     response = self._create_response(
               │20:48:09    weechat     | python: stdout/stderr (matrix):   File
               │                        | "/usr/local/lib/python3.9/dist-packages/nio/client/http_client.py", line
               │                        | 1277, in _create_response
               │20:48:09    weechat     | python: stdout/stderr (matrix):     response =
               │                        | request_class.from_dict(parsed_dict, *extra_data)
               │20:48:09    weechat     | python: stdout/stderr (matrix):   File
               │                        | "/usr/local/lib/python3.9/dist-packages/nio/responses.py", line 170, in
               │                        | wrapper
               │20:48:09    weechat     | python: stdout/stderr (matrix):     return f(cls, parsed_dict, *args,
               │                        | **kwargs)
               │20:48:09    weechat     | python: stdout/stderr (matrix):   File
               │                        | "/usr/local/lib/python3.9/dist-packages/nio/responses.py", line 1745, in
               │                        | from_dict
               │20:48:09    weechat     | python: stdout/stderr (matrix):     rooms =
               │                        | SyncResponse._get_room_info(parsed_dict["rooms"])
               │20:48:09    weechat     | python: stdout/stderr (matrix):   File
               │                        | "/usr/local/lib/python3.9/dist-packages/nio/responses.py", line 1688, in
               │                        | _get_room_info
               │20:48:09    weechat     | python: stdout/stderr (matrix):     for room_id, room_dict in
econd time                              | parsed_dict["invite"].items():
               │20:48:09    weechat     | python: stdout/stderr (matrix): KeyError: 'invite'
               │20:48:09    weechat =!= | python: error in function "receive_cb"
```

This is on Debian 11, python: 3.9.0+, WeeChat 3.0 [compiled on Nov 21 2020 07:34:12]

**Comment by poljar** [comment] 2021-09-02 10:00
You'll need to update your nio version 0.18.5+ has fixes for this.

**Comment by poljar** [comment] 2021-09-02 10:01
This is a duplicate of #284.

**Closed by poljar** 2021-09-02 10:01 UTC
