### ISSUE TITLE
FlowControlError in larger rooms

### ISSUE THREAD

**Issue by tommyskg** [poljar/weechat-matrix#40] opened 2019-02-07 21:52 UTC
I'm using nginx in front of Synapse with the http2 module. Config is as default as it can get.

    server {
    ssl on;
    ssl_certificate [...];
    ssl_certificate_key [...];

    listen 1234 ssl http2;
    listen [::]:1234 ssl http2;

Everything seems to work fine, except when posting to rooms with more than 30 participants. It seems to be an issue with the allowed data size somewhere. weechat-matrix outputs this nicely like follows, but is this a setting that is changed on the server or the client?

     python: stdout/stderr (matrix): h2.exceptions.FlowControlError: Cannot send 86311 bytes, flow control window is 65536.

**Comment by poljar** [comment] 2019-02-07 22:16
Is the room encrypted?
If the room is encrypted and there is a larger number of participants you are probably hitting this when sharing encryption keys with the participants.

This is a bug in matrix-nio. Splitting up the data to fit into the flow control window isn't done.

I don't know if there is a setting for nginx to increase the window,  if there is you could try to increase it while this is being fixed.

I'll try to prioritize that over the next few days.

**Comment by tommyskg** [comment] 2019-02-08 04:25
Indeed. That sounds reasonable. I ended up with what I assume is a todo in the source related to what you mention as well.

I browsed the Nginx http2 docs briefly, but seem quite sparse in this regards, but it’s no hurry on my part - so I’ll wait for the fix.

**Comment by poljar** [comment] 2019-02-10 11:17
Ok, there is a nio branch that hopefully fixes this. Could you please test this?
The branch is [here](https://github.com/poljar/matrix-nio/tree/flowcontrol).

**Comment by tommyskg** [comment] 2019-02-10 13:22
Seems that it solves something, but now I get disconnected when pressing send.

Smaller rooms still functions. 

Anywhere I can get the debug data from file?

**Comment by poljar** [comment] 2019-02-10 16:56
You can enable debug output in the settings. Set `matrix.network.debug_category` to http and `matrix.network.debug_level` to debug.

After reproducing the disconnect please post the output.

**Comment by tommyskg** [comment] 2019-02-10 18:40
I had an issue with nio/http.py#482 which produced way more debug data than my buffer could handle. Thus, the question if a log file was present or an option somewhere made sense.

However, commenting that debug message, leaves me with the following excerpt of what I think is possibly the issue (it still was a lot of log lines). In this case, could it be that stream 13 is the issue? 

    1931 | nio.http: Sending data: stream id: 5; request size: 30; window size: 65536; max frame size 16777215
    1931 | nio.http: Sending data: stream id: 7; request size: 0; window size: 65536; max frame size 16777215
    1931 | nio.http: Sending data: stream id: 9; request size: 16; window size: 65536; max frame size 16777215
    1931 | nio.http: Sending data: stream id: 11; request size: 876; window size: 65536; max frame size 16777215
    1931 | nio.http: Sending data: stream id: 13; request size: 83497; window size: 65536; max frame size 16777215
    1931 | nio.http: Sending data: stream id: 1; request size: 0; window size: 65535; max frame size 16384

**Comment by tommyskg** [comment] 2019-02-10 18:45
I can replicate it again, and it is the last message before the disconnect and the the new stream id 1. Happens every time.

    1943 | nio.http: New stream id 155
    1943 | nio.http: Sending data: stream id: 155; request size: 83497; window size: 65536; max frame size 16777215

**Comment by poljar** [comment] 2019-02-11 12:30
I checked the flow-control logic with uploads, it seems to work fine. I suspect the issue that you are seeing now is that we are hitting the event size limit described [here](https://matrix.org/docs/spec/client_server/r0.4.0.html#size-limits). 
You should get a HTTP error from that request right before it disconnects.

This will need more work.

**Comment by tommyskg** [comment] 2019-02-11 12:46
With the debug settings specified above I get no HTTP errors. Anything else that is needed from me?

Just out of curiosity, how does Riot handle that limit?

**Comment by poljar** [comment] 2019-02-11 12:49
Nothing else needed.

Riot shares the keys using multiple HTTP requests.

**Comment by tommyskg** [comment] 2019-02-11 12:55
Just to add, the console does show a generic error like the following:

    nio.http: Handling Http2 event: <StreamEnded stream_id:89>
    matrix: Error while writing to socket
    matrix: disconnecting from server...

**Comment by poljar** [comment] 2019-02-11 12:58
That's fine, seems like Synapse doesn't return a HTTP error, it just drops the connection.

**Comment by poljar** [comment] 2019-02-12 11:14
Ok, could you try out the latest weechat-matrix master and the latest matrix-nio from [this](https://github.com/poljar/matrix-nio/tree/flowcontrol) branch?

**Comment by tommyskg** [comment] 2019-02-12 12:05
Pulled both those updates, and: that did something, but there seems to be a loop gone wrong somewhere. Synapse kill the session after 1997 streams:

     nio.http: Sending data: stream id: 1997; request size: 15; window size: 65536; max frame size 16777215

**Comment by tommyskg** [comment] 2019-02-12 12:13
It breaks all the minor channels as well, with loads of small requests. Sending to one person ends up with 1715 requests/streams with a request size of 15 and 76 alternating.

**Comment by poljar** [comment] 2019-02-12 12:58
Did something? We're not particularly interested in the HTTP layer anymore unless the flow-control logic is failing for some reason. But you shouldn't really hit the frame splitting anymore since the key sharing request is split up into multiple requests.

Can you describe what works and what doesn't? The small requests size is unlikely to be a key sharing request.

Maybe try to switch the debug category to `client` or you can even setup mitmproxy to watch the requests as they leave weechat.

**Comment by tommyskg** [comment] 2019-02-12 13:35
By something, I mean that the many streams weren't there before. Previously only a few were exchanged. Switching category to ``client`` what I see is quite a lot of:

    nio.client: Received response of type: RequestType.share_group_session
    nio.client: Received new response of type ShareGroupSessionResponse
    nio.client: Received response of type: RequestType.keys_claim

**Comment by poljar** [comment] 2019-02-12 13:50
This is helpful. A user that you are sharing a room with doesn't have one-time keys on the server so creating a peer to peer session with him fails. The peer to peer session is necessary to share the group session keys.

The logic for this worked thus far because we tried to share a group session, we couldn't since a peer to peer session is missing so we tried to claim one-time keys, that failed as well but we continued to share the group session by ignoring the missing peer to peer sessions.

Since we now make multiple group session sharing requests a key claim is tried for every second group session sharing request.

Thanks. Will get back when i figure out how to fix this.

**Comment by poljar** [comment] 2019-02-13 12:10
Another patch has landed on the [flow-control](https://github.com/poljar/matrix-nio/tree/flowcontrol) branch. 

I tested that it fixes the infinitely looping behavior, if you could give that patch a spin and confirm that it's fixed, that would be great.

**Comment by tommyskg** [comment] 2019-02-14 06:47
Works like a charm \o/

**Comment by poljar** [comment] 2019-02-14 16:54
Great to hear that. 

I merged the flow-control branch into the master branch of nio. Closing this as it's fixed.

Thanks for testing.

**Closed by poljar** 2019-02-14 16:54 UTC
Labels: bug
