### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'lag'

### ISSUE THREAD

**Issue by zetorian** [poljar/weechat-matrix#50] opened 2019-02-18 01:49 UTC
Upon loading the module in weechat (python2) the weechat buffer constantly spits out error messages of the type in the title for various functions, the script does not load and cannot be used.

```
  =!= python: error in function "matrix_timer_cb"
  python: stdout/stderr (matrix): Traceback (most recent call last):
  python: stdout/stderr (matrix):   File "/home/zet/.weechat/python/matrix/utf.py", line 91, in wrapper
  python: stdout/stderr (matrix):     return function(*decode_from_utf8(args), **decode_from_utf8(kwargs))
  python: stdout/stderr (matrix):   File "/home/zet/.weechat/python/matrix/server.py", line 1614, in matrix_timer_cb
  python: stdout/stderr (matrix):     server.lag = server.client.lag * 1000
  python: stdout/stderr (matrix): AttributeError: 'NoneType' object has no attribute 'lag'
  =!= python: error in function "matrix_timer_cb"
  python: stdout/stderr (matrix): Traceback (most recent call last):
  python: stdout/stderr (matrix):   File "/home/zet/.weechat/python/matrix/utf.py", line 91, in wrapper
  python: stdout/stderr (matrix):     return function(*decode_from_utf8(args), **decode_from_utf8(kwargs))
  python: stdout/stderr (matrix):   File "/home/zet/.weechat/python/matrix/server.py", line 1614, in matrix_timer_cb
  python: stdout/stderr (matrix):     server.lag = server.client.lag * 1000
  python: stdout/stderr (matrix): AttributeError: 'NoneType' object has no attribute 'lag'
  =!= python: error in function "matrix_timer_cb"
  python: stdout/stderr (matrix): Traceback (most recent call last):
  python: stdout/stderr (matrix):   File "/home/zet/.weechat/python/matrix/utf.py", line 91, in wrapper
  python: stdout/stderr (matrix):     return function(*decode_from_utf8(args), **decode_from_utf8(kwargs))
  python: stdout/stderr (matrix):   File "/home/zet/.weechat/python/matrix/server.py", line 1614, in matrix_timer_cb
  python: stdout/stderr (matrix):     server.lag = server.client.lag * 1000
  python: stdout/stderr (matrix): AttributeError: 'NoneType' object has no attribute 'lag'
  =!= python: error in function "matrix_timer_cb"
```
the matrix server buffer loads, but the actual rooms do not, I have bisected the git tree, this appears to have been introduced in:
https://github.com/poljar/weechat-matrix/commit/c68093900501ada1fa80689c6309776d455e2ad6

If my understanding is correct, this is likely something that simply needs a typecast

**Comment by poljar** [comment] 2019-02-18 07:49
Are you sure this isn't a duplicate of #48? This script requires the latest master of matrix-nio.

A typecast won't help here, we can't cast `None` to a `HttpClient` object. The object is created at load time, so something isn't loading properly.

**Comment by zetorian** [comment] 2019-02-18 20:46
I was using the make target mentioned in that post thread. for whatever reason the upgrade, probably because I did it with weechat's `/upgrade`, caused the configuration fields to become blank in matrix.conf, I use git versioning for my dotfiles so when i started bisecting everything came back, weird but my own falt.

sorry for any time wasted.

**Closed** 2019-02-18 20:47 UTC
