### ISSUE TITLE
Can't connect to a homeserver if the server url uses a sub path

### ISSUE THREAD

**Issue by michaelnew** [poljar/weechat-matrix#37] opened 2019-02-03 08:05 UTC
My homeserver lives at `mikenew.io/_matrix`, and if try to connect to it, weechat comes up with a url that looks like `mikenew.io/_matrix:443`, which is not a valid url. Should be `mikenew.io:443/_matrix`.

Looks like it's happening here: https://github.com/poljar/weechat-matrix/blob/master/matrix/server.py#L323

**Comment by michaelnew** [comment] 2019-02-03 08:39
@poljar no, mine actually is `https:/mikenew.io/_matrix/_matrix`. Using `/_matrix` was in retrospect a dumb way to name it, but it needed to be on a subpath either way because https://mikenew.io is being used for something else. 

My dumb naming decisions aside, sticking the port number onto the end of the hostname won't work for any server that uses a subpath.

**Comment by michaelnew** [comment] 2019-02-03 21:37
Hmm, still no. It looks like `hook_connect` just doesn't want to make a connection if there's a sub path. If I plug the address in directly it fails with `matrix: Name or service not known not found`:
```
W.hook_connect(
    self.config.proxy,
    "mikenew.io/_matrix",
    self.config.port,
    1,
    0,
    "",
    "connect_cb",
    self.name,
)
```
If I instead use `mikenew.io` it actually start a connection, but fails with an invalid certificate error (which is correct, because that points to a nextcloud instance with a different certificate). The documentation is [here](https://weechat.org/files/doc/stable/weechat_plugin_api.en.html#_hook_connect), but it doesn't say much about it.

Best I can tell, things resolve down to [this function](https://github.com/weechat/weechat/blob/2b0057239b15204a787e8e81497e150d163089dd/src/core/wee-network.c#L751), but it's really getting down into the weeds and I can't sort out what's happening there. I think I may try to set up a reverse proxy to my matrix server on a nonstandard port to see if I can connect to it that way.

If you think there's something else going on then let me know, otherwise feel free to close the issue since it looks like the problem doesn't really have to do with this plugin. And thanks for the help.

**Comment by poljar** [comment] 2019-02-03 22:02
Right, I forgot that this config option is directly used in hook_connect(). You need to put mikenew.io in  [here](https://github.com/poljar/weechat-matrix/blob/master/main.py#L183) as well, that's why you get a certificate error.

I pushed another commit to the same branch, could you try this one b884536e7e329a9ea91b0908dddcbaa67c01a8da?

**Comment by poljar** [comment] 2019-02-03 23:42
Sadly this will need some nio changes as well. I'll get back when i make those.

**Comment by poljar** [comment] 2019-02-04 10:05
OK, this should work now with 71ffee9036188728e75429f445cca43d41dd8022, and latest nio master. If you could give that a spin that would be great.

**Comment by michaelnew** [comment] 2019-02-04 21:50
Okay, progress! So it connects, logs in, loads up my rooms, and I'm actually able to send messages. After a little while (sometimes a few seconds, sometimes a few minutes) I get `matrix: Error while reading from socket` and it disconnects. I can't tell what triggers the error.

Let me know if there's anything I can look into to try and debug.
```
python: loading script "/home/mikenew/.weechat/python/matrix.py"
python: registered script "matrix", version 0.1 (matrix chat plugin)
matrix: Connecting to mikenew.io:443 (SSL)...
matrix: Doing SSL handshake...
matrix: Connected using TLSv1.3, and 256 bit TLS_AES_256_GCM_SHA384 cipher suite.
matrix: received certificate
 - certificate info:
    - subject: organizationalUnitName=Domain Control Validated,
        organizationalUnitName=PositiveSSL, commonName=mikenew.io,
        serial number BF54618E22DBF9E1EBF31D21EDB35063
    - issuer: countryName=GB, stateOrProvinceName=Greater Manchester,
        localityName=Salford, organizationName=COMODO CA Limited,
        commonName=COMODO RSA Domain Validation Secure Server CA
    - key info: RSA key 2048 bits, signed using
        sha256WithRSAEncryption
    - period of validity:
        Begins on:  Mar 30 00:00:00 2018 GMT
        Expires on: Mar 30 23:59:59 2019 GMT
    - fingerprints:
        SHA1:   F1:7D:42:9A:CE:E1:46:F4:E7:B7:56:43:3E:FF:70:CF:F5:BC:CC:4F
        SHA256: 12:49:6A:FB:0A:CC:31:DD:E7:14:24:75:57:69:BD:D6:91:99:08:D8:CF:07:03:08:ED:C5:94:12:94:84:1A:14
matrix: Logging in...
matrix: Logged in as @mike_new:mikenew.io
matrix: Error while reading from socket
matrix: disconnecting from server...
matrix: disconnected from server
matrix: reconnecting to server in 10 seconds
```

**Comment by dkasak** [comment] 2019-02-04 21:57
Take a look at `matrix.look.debug_level`. You can set it to `info` or `debug` and then try reproducing the bug to see if there's anything useful in the output. There's also `matrix.look.debug_category` to filter by message category and `matrix.look.debug_buffer` to get a separate buffer for debug messages.

**Comment by dkasak** [comment] 2019-02-04 22:11
Though the error message you're getting looks like the other end simply closing the connection. [See here](https://github.com/poljar/weechat-matrix/issues/27#issuecomment-454856153).

**Comment by dkasak** [comment] 2019-02-05 08:09
I agree that it would be nice if both of these quirks were handled eventually.

The first quirk is tracked in #30 and could be solved by having smarter logic in case of a disconnect, such as:

* having a configurable reconnect delay (done)
* allowing you to send (greyed out) messages while disconnected
* potentially not displaying the error message for transient disconnects and only doing it if it is unable to reconnect after several tries or after some amount of time has passed

The second quirk is related to the fact that weechat-matrix doesn't yet persist information about what were the last things fetched the last time it was connected. This could likely be implemented by remembering the last sync token and only asking for events that happened after that sync token when connecting for the first time in a given weechat run. Please do open the issue.

**Comment by poljar** [comment] 2019-02-05 14:38
Closing, this is now fixed.

**Closed by poljar** 2019-02-05 14:38 UTC
